-- =============================================================================
--  Roteiro da entrevista: uma linha por campo da API.
--  Reaplicável — atualiza texto/tipo sem duplicar.
-- =============================================================================

SET search_path TO peticoes, public;

INSERT INTO peticoes.perguntas
    (campo, coluna, secao, ordem, texto, tipo, opcoes, obrigatorio, efeito_ausencia)
VALUES
-- ------------------------------------------------------------- reclamante ---
('RECL_NOME','recl_nome','reclamante',10,
 'Qual o seu nome completo?','texto',NULL,true,
 'sem ele a API recusa a requisição (422)'),
('RECL_CPF','recl_cpf','reclamante',20,'Qual o seu CPF?','texto',NULL,false,
 'qualificação sai incompleta'),
('RECL_RG','recl_rg','reclamante',30,'Qual o número do seu RG?','texto',NULL,false,
 'qualificação sai incompleta'),
('RECL_PIS','recl_pis','reclamante',40,'Qual o seu número do PIS?','texto',NULL,false,
 'qualificação sai incompleta'),
('RECL_CTPS','recl_ctps','reclamante',50,'Qual o número da sua CTPS?','texto',NULL,false,
 'qualificação sai incompleta'),
('RECL_SERIE','recl_serie','reclamante',60,'E a série da CTPS?','texto',NULL,false,
 'qualificação sai incompleta'),
('RECL_NASC','recl_nasc','reclamante',70,'Qual a sua data de nascimento?','data',NULL,false,
 'qualificação sai incompleta'),
('RECL_FILIACAO','recl_filiacao','reclamante',80,
 'Nome do seu pai e da sua mãe?','texto',NULL,false,'qualificação sai incompleta'),
('RECL_ENDERECO','recl_endereco','reclamante',90,
 'Qual o seu endereço completo (rua, número, bairro, cidade/UF)?','texto',NULL,false,
 'município da prestação precisa ser informado à parte'),
('RECL_CEP','recl_cep','reclamante',100,'Qual o CEP?','texto',NULL,false,
 'qualificação sai incompleta'),
('RECL_NACIONALIDADE','recl_nacionalidade','reclamante',110,
 'Qual a sua nacionalidade?','texto',NULL,false,'qualificação sai incompleta'),
('RECL_ESTADOCIVIL','recl_estadocivil','reclamante',120,
 'Qual o seu estado civil?','escolha',
 ARRAY['solteiro','casado','divorciado','viúvo','união estável'],false,
 'qualificação sai incompleta'),
('email','email','reclamante',130,'Qual o seu e-mail?','texto',NULL,false,
 'qualificação sai incompleta'),

-- ------------------------------------------------------------- reclamadas ---
('RECL1_NOME',NULL,'reclamadas',200,
 'Qual o nome da empresa em que você trabalhava?','texto',NULL,false,
 'peça sem a empregadora identificada'),
('RECL1_CNPJ',NULL,'reclamadas',210,
 'Sabe o CNPJ dessa empresa? (ajuda a identificar a categoria)','texto',NULL,false,
 'categoria e convenção coletiva ficam menos precisas'),
('RECL1_LOGRADOURO',NULL,'reclamadas',220,
 'Qual o endereço da empresa (rua e número)?','texto',NULL,false,
 'endereço da ré fica incompleto'),
('RECL1_ENDCOMPL',NULL,'reclamadas',230,
 'E a cidade/UF e CEP da empresa?','texto',NULL,false,
 'endereço da ré fica incompleto'),
('RECL2_NOME',NULL,'reclamadas',240,
 'Você prestava serviço para outra empresa (tomadora)? Qual o nome?','texto',NULL,false,
 'sem responsabilidade subsidiária na peça'),
('RECL2_CNPJ',NULL,'reclamadas',250,'Sabe o CNPJ da tomadora?','texto',NULL,false,
 'endereço/qualificação da tomadora fica incompleta'),
('RECL2_ENDCOMPL',NULL,'reclamadas',260,
 'Em qual cidade/UF você prestava serviço para ela?','texto',NULL,false,
 'competência é definida por outro critério'),
('RECL3_NOME',NULL,'reclamadas',270,
 'Havia uma terceira empresa envolvida? Qual?','texto',NULL,false,
 'terceira ré não entra na peça'),
('RECL3_CNPJ',NULL,'reclamadas',280,'CNPJ da terceira empresa?','texto',NULL,false,
 'qualificação da terceira ré fica incompleta'),
('RECL3_ENDCOMPL',NULL,'reclamadas',290,'Cidade/UF da terceira empresa?','texto',NULL,false,
 'qualificação da terceira ré fica incompleta'),

-- --------------------------------------------------------------- contrato ---
('DATA_ADMISSAO','data_admissao','contrato',300,
 'Quando você foi admitido? (dia/mês/ano)','data',NULL,false,
 'sem base para avos, FGTS e projeção'),
('DATA_RESCISAO','data_rescisao','contrato',310,
 'E qual foi o último dia de trabalho?','data',NULL,false,
 'sem base para avos, FGTS e projeção'),
('FUNCAO','funcao','contrato',320,
 'Qual função você exercia?','texto',NULL,false,
 'categoria indefinida; não distingue desvio de acúmulo de função'),
('SALARIO','salario','contrato',330,
 'Qual era o seu salário-base?','moeda',NULL,false,
 'usa o piso da categoria na convenção coletiva'),
('tipo_dispensa','tipo_dispensa','contrato',340,
 'Como terminou o contrato?','escolha',
 ARRAY['sem_justa_causa','rescisao_indireta','coacao_demissao',
       'reversao_justa_causa','acordo'],false,
 'assume dispensa sem justa causa'),

-- ---------------------------------------------------------------- jornada ---
('escala','escala','jornada',400,
 'Qual era a sua escala? (ex.: 12x36, 6x1)','texto',NULL,false,
 'jornada apurada só pelo horário informado'),
('JORNADA_HORARIO','jornada_horario','jornada',410,
 'Qual era o horário de trabalho? (ex.: das 19h às 07h)','texto',NULL,false,
 'sem base para horas extras e adicional noturno'),
('tem_adic_noturno','tem_adic_noturno','jornada',420,
 'Você trabalhava entre 22h e 5h da manhã?','booleano',NULL,false,
 'inferido a partir do horário informado'),
('finais_semana','finais_semana','jornada',430,
 'Trabalhava em domingos e feriados?','booleano',NULL,false,
 'sem pedido de dobra de domingos/feriados'),
('intervalo_suprimido','intervalo_suprimido','jornada',440,
 'O seu intervalo de almoço era suprimido ou reduzido?','booleano',NULL,false,
 'sem pedido de intervalo intrajornada'),
('INTERVALO_GOZADO','intervalo_gozado','jornada',450,
 'Quanto tempo de intervalo você conseguia realmente fazer?','texto',NULL,false,
 'usa a supressão total do intervalo'),
('media_horas_extras','media_horas_extras','jornada',460,
 'Em média, quantas horas extras por dia? (ex.: até 1 hora)','texto',NULL,false,
 'sem estimativa de horas extras'),
('periodo_antecedente','periodo_antecedente','jornada',470,
 'Quantos minutos antes do horário você já estava trabalhando?','numero',NULL,false,
 'minutos residuais não entram no cálculo'),
('periodo_sucedente','periodo_sucedente','jornada',480,
 'E quantos minutos depois do fim da jornada?','numero',NULL,false,
 'minutos residuais não entram no cálculo'),

-- --------------------------------------------------- folgas e benefícios ----
('folgas_trabalhadas','folgas_trabalhadas','folgas',500,
 'Você trabalhava nas suas folgas?','booleano',NULL,false,
 'sem pedido de folgas trabalhadas'),
('FT_QTD_MEDIA','ft_qtd_media','folgas',510,
 'Quantas folgas por mês, em média? (aceita faixa, ex.: 5 a 6)','faixa',NULL,false,
 'folgas trabalhadas sem quantificação'),
('VAL_FT','val_ft','folgas',520,
 'Quanto recebia por folga trabalhada? (ex.: R$ 180 a R$ 200)','faixa',NULL,false,
 'folgas trabalhadas sem valor de referência'),
('vale_refeicao','vale_refeicao','folgas',530,
 'Recebia vale-refeição?','booleano',NULL,false,'benefício não considerado'),
('vale_alimentacao','vale_alimentacao','folgas',540,
 'Recebia vale-alimentação?','booleano',NULL,false,'benefício não considerado'),
('vale_transporte','vale_transporte','folgas',550,
 'Recebia vale-transporte?','booleano',NULL,false,'benefício não considerado'),

-- ------------------------------------------------------ teses e documentos ---
('acumulo_funcao','acumulo_funcao','teses',600,
 'Você exercia outras funções além da sua?','booleano',NULL,false,
 'sem pedido de acúmulo/desvio de função'),
('funcoes_acumuladas','funcoes_acumuladas','teses',610,
 'Quais atividades a mais você fazia?','texto_longo',NULL,false,
 'acúmulo alegado sem descrição das atividades'),
('tem_periculosidade','tem_periculosidade','teses',620,
 'O trabalho envolvia risco (energia, inflamáveis, armas)?','booleano',NULL,false,
 'sem adicional de periculosidade'),
('tem_insalubridade','tem_insalubridade','teses',630,
 'Havia agentes insalubres (calor, ruído, químicos, biológicos)?','booleano',NULL,false,
 'sem adicional de insalubridade'),
('tem_doenca','tem_doenca','teses',640,
 'Você desenvolveu alguma doença por causa do trabalho?','booleano',NULL,false,
 'sem capítulo de doença ocupacional'),
('gratificacao','gratificacao','teses',650,
 'Recebia gratificação de função? Qual valor?','texto',NULL,false,
 'gratificação não integra a base de cálculo'),
('assiduidade','assiduidade','teses',660,
 'Recebia prêmio de assiduidade?','booleano',NULL,false,
 'prêmio não integra a base de cálculo'),
('desconto_indevido','desconto_indevido','teses',670,
 'Havia descontos indevidos no seu salário?','booleano',NULL,false,
 'sem pedido de devolução de descontos'),
('desconto_qual','desconto_qual','teses',680,
 'Quais descontos eram feitos?','texto',NULL,false,
 'descontos alegados sem especificação'),
('holerites','holerites','documentos',700,
 'Você tem os seus holerites?','booleano',NULL,false,
 'sem prova documental de remuneração'),
('espelho_ponto','espelho_ponto','documentos',710,
 'Tem os espelhos de ponto?','booleano',NULL,false,
 'sem prova documental de jornada'),
('fatos_narrados','fatos_narrados','relato',800,
 'Conte com as suas palavras o que aconteceu no trabalho.','texto_longo',NULL,false,
 'capítulos narrativos ficam genéricos, sem os fatos do caso')

ON CONFLICT (campo) DO UPDATE SET
    coluna          = EXCLUDED.coluna,
    secao           = EXCLUDED.secao,
    ordem           = EXCLUDED.ordem,
    texto           = EXCLUDED.texto,
    tipo            = EXCLUDED.tipo,
    opcoes          = EXCLUDED.opcoes,
    obrigatorio     = EXCLUDED.obrigatorio,
    efeito_ausencia = EXCLUDED.efeito_ausencia,
    ativo           = true;
